version: '3'
services:

  config-server:
    build: ./config-server
#    dockerfile: Dockerfile
#    image: config-server
    ports:
      - "9000:9000"

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  room-services:
    build: ./room-services
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka-server:8761/eureka
      - EUREKASERVER_PORT=8761
      - CONFIGSERVER_URI=http://config-server:9000
      - CONFIGSERVER_PORT=9000
    ports:
      - "8101:8101"
    depends_on:
      - config-server
      - eureka-server

  guest-services:
    build: ./guest-services
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka-server:8761/eureka
      - EUREKASERVER_PORT=8761
      - CONFIGSERVER_URI=http://config-server:9000
      - CONFIGSERVER_PORT=9000
    ports:
      - "8102:8102"
    depends_on:
      - config-server
      - eureka-server

  reservation-services:
    build: ./reservation-services
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka-server:8761/eureka
      - EUREKASERVER_PORT=8761
      - CONFIGSERVER_URI=http://config-server:9000
      - CONFIGSERVER_PORT=9000
    ports:
      - "8103:8103"
    depends_on:
      - config-server
      - eureka-server

  reservation-business-services:
    build: ./reservation-business-services
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka-server:8761/eureka
      - EUREKASERVER_PORT=8761
      - CONFIGSERVER_URI=http://config-server:9000
      - CONFIGSERVER_PORT=9000
      - ROOMSERVICES_PORT=8101
      - GUESTSERVICES_PORT=8102
      - RESERVATIONSERVICES_PORT=8103
    ports:
      - "8500:8500"
    depends_on:
      - room-services
      - guest-services
      - reservation-services

  reservation-webapp:
    build: ./reservation-webapp
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka-server:8761/eureka
      - CONFIGSERVER_URI=http://config-server:9000
      - CONFIGSERVER_PORT=9000
      - RESERVATIONBUSINESSSERVICES_PORT=8500
    ports:
      - "8600:8600"
    depends_on:
      - reservation-business-services
